name: Backport
on:
  pull_request_target:
    types:
      - closed
      #- labeled


permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  backport:
    uses: sarahmccarthy123/.github/.github/workflows/reusable-sarah-backport.yml@c87b299296feda459b7ffc7ad31433176cb18871
    with:
      label_pattern: "^backport (.+)$"
    #secrets:
    #  APP_ID: ${{ secrets.APP_ID }}
    #  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      
