name: Backport
on:
  pull_request_target:
    types:
      - closed



permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  backport:
    uses: sarahmccarthy123/.github/.github/workflows/reusable-sarah-backport.yml@206c8d5867666f3bae0c109651154e870ed84d0b
    with:
      label_pattern: "^backport (.+)$"
    #secrets:
    #  APP_ID: ${{ secrets.APP_ID }}
    #  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      
