name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  backport:
    uses: sarahmccarthy123/.github/.github/workflows/resuable-sarah-backport.yml@47063497b05669623fb6752f64641c640770b926
    with:
      label_pattern: "^backport (.+)$"
    #secrets:
    #  APP_ID: ${{ secrets.APP_ID }}
    #  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      
